<a href="https://colab.research.google.com/github/Anniikett/ANN-for-Regression_Sklearn/blob/main/Data_Structures_and_Numpy_31st_July_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data structures in Python

# Numbers

In [ ]:
a=5
print(type(a))
a=12.5
print(type(a))
a=10+5j
print(type(a))

<class 'int'>
<class 'float'>
<class 'complex'>


In [ ]:
import math

In [ ]:
print(math.sqrt(4))
print(math.floor(10.7))  #10.7 it will make sure that the value in point will get down only.
print(math.ceil(10.7))   #10.7 it will make sure that the value in point will goes up only everytime.
print(math.pow(2,3))
print(math.factorial(6))
#print(round(math.pi,0))
print(math.pi)
print(round(math.pi,2))

2.0
10
11
8.0
720
3.141592653589793
3.14


In [ ]:
area_of_circle=math.pi*10*10
print(area_of_circle)

314.1592653589793


In [ ]:
import numpy
numpy.sqrt

<ufunc 'sqrt'>

# Strings


In [ ]:
my_string = 'Imarticus:Aniket Programming'
print(my_string)

print()

"""
this is
a comment"""

my_string = """Python is a programming language.\nPython is interesting.\nAniket is new in it.\nLets do boom baam for next 2 years."""
print(my_string)


Imarticus:Aniket Programming

Python is a programming language.
Python is interesting.
Aniket is new in it.
Lets do boom baam for next 2 years.


In [ ]:
#slicing
my_string = "Python is a programming language. Python is interesting."
print(my_string[0])
print(my_string[-3])
#[inclusive:exclusive]
print(my_string[3:10])
print(my_string[:25])
print(my_string[25:])
print(my_string[:])
#print(my_string[54])
print(len(my_string))
print(my_string[5:8],my_string[10])

In [ ]:
my_string.split(sep=" ")

In [ ]:
#strings are immutable
my_string[3]="B"

In [ ]:
list(my_string)

In [ ]:
my_string=my_string.replace("in","N")
print(my_string)

In [ ]:
del my_string

In [ ]:
print(my_string)

# Lists

In [ ]:
# Python List

mylist1=[1,3,5,4,2]

mylist2 = [1, 4.2, "python" ,4.2]

print(mylist1)
print(mylist2)
print(type(mylist2))

[1, 3, 5, 4, 2]
[1, 4.2, 'python', 4.2]
<class 'list'>


In [ ]:
# use of slicing operator
a = [10,20,30,40,50,60,70,80]

print(a[2])

print(a[0:3])

print(a[5:])
print(a[2],a[5])


30
[10, 20, 30]
[60, 70, 80]
30 60


In [ ]:
#lists are mutable (Mutable = Can be modified i.e. add/remove/update after initialization)
#replacing an element on the basis of index number
a[5]="aniket"
print(a)

[10, 20, 30, 'aniket', 50, 'aniket', 70, 80]


In [ ]:
#appending multiple elements
my_list=[1,3,6,9]

my_new_list=[4,5,6,7,8]

my_list.append("xyz")
my_list.extend(my_new_list)

print(my_list)

[1, 3, 6, 9, 'xyz', 4, 5, 6, 7, 8]


In [ ]:
my_list.insert(7,"abc")
print(my_list)

[1, 3, 6, 9, 'abc', 'xyz', 4, 'abc', 5, 6, 7, 8]


In [ ]:
my_list.remove(6)
print(my_list)


[1, 3, 9, 'abc', 'xyz', 4, 'abc', 5, 6, 7, 8]


In [ ]:
del my_list[2]
my_list

[1, 3, 'abc', 'xyz', 4, 'abc', 5, 6, 7, 8]

# Tuples

In [ ]:
a = (5,'python',[1,"alex",3], 27.9,5)
print(a)
print(type(a))
print(a[2][1][3]) #alex have take in that (3) is x in that


(5, 'python', [1, 'alex', 3], 27.9, 5)
<class 'tuple'>
x


In [ ]:
list1=[1,2,3]
tuple1=tuple(list1)
print(tuple1)

(1, 2, 3)


In [ ]:
#tuple is immutable
#a[2]=0

del a


# Sets

In [ ]:
my_set = {1,2.0,3,4,3,2,10,"alex",38,72,16}
print(my_set)

{1, 2.0, 3, 4, 38, 72, 10, 16, 'alex'}


In [ ]:
#my_set[3]

In [ ]:
#Adding elements
my_set = {1,3}
print("my_set:",my_set)

my_set.add(8)
print("my_set2:",my_set)

my_set.update([6,8,1,4,2])
print("my_set3:",my_set)

#deleting elements
my_set.remove(6)
print("my_set4:",my_set)



my_set: {1, 3}
my_set2: {8, 1, 3}
my_set3: {1, 2, 3, 4, 6, 8}
my_set4: {1, 2, 3, 4, 8}


In [ ]:
#Union and intersection

A = [1, 2, 3, 4, 5,9]
B = (4, 5, 6, 7, 8,10)

setA=set(A)
setB=set(B)

print(setA | setB)
print(setA.union(setB))

print(setA & setB)
print(setA.intersection(setB))

print(setA-setB)
print(setB-setA)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
{4, 5}
{4, 5}
{1, 2, 3, 9}
{8, 10, 6, 7}


# Dictionaries

In [ ]:
# Creating a dictionary
my_d1 = {1: 'A', "B": 2}
print(my_d1)

my_d2 = {"name": ("John","Priya","Alex"), "ID": [2,4], "Marks":[34,45,38],"Marks":[47,45,32]}
print(my_d2)
print(my_d2["name"])
print(my_d2["name"][0],my_d2["ID"][0],my_d2["Marks"][0])
print(my_d1[1])
#print(my_d2[0])

{1: 'A', 'B': 2}
{'name': ('John', 'Priya', 'Alex'), 'ID': [2, 4], 'Marks': [47, 45, 32]}
('John', 'Priya', 'Alex')
John 2 47
A


In [ ]:
my_d={"Name":"Priya","age":[12,27,30]}
my_d['age'][1] = 28
print(my_d)

my_d['address'] = ['Mumbai','Pune']
print(my_d)

{'Name': 'Priya', 'age': [12, 28, 30]}
{'Name': 'Priya', 'age': [12, 28, 30], 'address': ['Mumbai', 'Pune']}


In [ ]:
del my_d["age"][1]
print(my_d)

{'Name': 'Priya', 'age': [12, 30], 'address': ['Mumbai', 'Pune']}


In [ ]:
my_d.values()

dict_values(['Priya', [12, 30], ['Mumbai', 'Pune']])

In [ ]:
my_d.keys()

dict_keys(['Name', 'age', 'address'])

# NumPy

## Introduction

- NumPy is a general-purpose array-processing package
- Travis Oliphant First Released in 1995 (Released as __Numeric__; Changed to NumPy in 2006). It is written in Python and C
- NumPy is cross-platform and BSD-licensed. Often used with packages such as Matplotlib (plotting library) and SciPy (Scientific Python). Sometimes it is seen as an alternative to MATLAB. The term ‘Numpy’ is a portmanteau of the words ‘NUMerical’ and ‘PYthon
- It is a library that allows end-users to create **high-performance multidimensional array objects** and manipulate these arrays (objects)
- NumPy provides a gamut of high-level functions for mathematical and logical operations, Fourier transforms, array shape manipulations, linear algebra operations, random number generation, etc.

## Numpy Installation

Once you have installed `pip`, i.e., the default python package manager; installing numpy is straightforward.

`pip install numpy`

## Numpy Import

Conventionally, numpy is imported as `np` as shown below

In [ ]:
import numpy as np
print(np.__version__)    # Check the numpy version

## Basic Usage

In [ ]:
# Create a 3 x 3 array, with all elements initialized to 1. Default data type for array is float.
b = np.ones((3, 3))
print(b)
type(b)    # print datatype of b
b.dtype    # print datatype of elements in b

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


dtype('float64')

In [ ]:
# Modify the data type of array elements
c = np.ones((3, 3), dtype=int)
print(c)
type(c)
c.dtype

[[1 1 1]
 [1 1 1]
 [1 1 1]]


dtype('int64')

In [ ]:
d = np.array([11 + 12j, 13 + 14j, 15 + 16j])    # numpy array with complex data type
d.dtype

dtype('complex128')

In [ ]:
e = np.array([False, True, True, False, False, True])    # numpy array with boolean data type
e.dtype

dtype('bool')

In [ ]:
f = np.array(['Welcome', 'To', 'Numpy'])
f.dtype    # Unicode string of 7 characters

dtype('<U7')

In [ ]:
len(f)    # get the length of the array

3

In [ ]:
# Shortcut to create an array of numbers
ar = np.arange(10)
print(ar)


print(np.arange(start=1,stop=10,step=3))

[0 1 2 3 4 5 6 7 8 9]
[1 4 7]


In [ ]:
# Indexing on 1-D array - This is similar to Python lists
ar[1], ar[3], ar[-1]

(1, 3, 9)

In [ ]:
# Arrays are assigned by reference

a = np.array([10, 11, 12, 13]) # create array
print(a)       # print a's value
print(type(a)) # type of variable a
print(id(a))

b = a    # reference assignment
print(id(b))
b[0] = 20
print(a[0])

[10 11 12 13]
<class 'numpy.ndarray'>
140648459259776
140648459259776
20


In [ ]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)
print(a.ndim)
print(a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [ ]:
a=np.array([((1,2,3),(4,5,6),(7,8,9)),((1,2,3),(4,5,6),(7,8,9))])
print(a)
print(a.ndim)
print(a.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
(2, 3, 3)


## Indexing and slicing

Indexes are tuples of numbers

In [ ]:
a = np.diag(np.arange(3))   # create a 3 by 3 array with diagonal elements set to 0, 1, 2
print(a)
a[2, 2]    # Indexing starts with 0. Here we are slicing one element in the second row and second column. We used a tuple 1, 1

[[0 0 0]
 [0 1 0]
 [0 0 2]]


2

In [ ]:
a[2, 1] = 12 # Update array element
a

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 12,  2]])

In [ ]:
print(a[1:, 0:2])  # We can use slicing concepts for all the dimensions!

[[ 0  1]
 [ 0 12]]


In [ ]:
ar = np.arange(10)
print(ar)
ar[:4]    # Slice, starting from zero and ending at three

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3])

In [ ]:
ar[::3]    # Slice every second element, starting from 0

array([0, 3, 6, 9])

## Transpose

In [ ]:
import numpy as np
help(np.transpose)

Help on function transpose in module numpy:

transpose(a, axes=None)
    Reverse or permute the axes of an array; returns the modified array.
    
    For an array a with two axes, transpose(a) gives the matrix transpose.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : tuple or list of ints, optional
        If specified, it must be a tuple or list which contains a permutation of
        [0,1,..,N-1] where N is the number of axes of a.  The i'th axis of the
        returned array will correspond to the axis numbered ``axes[i]`` of the
        input.  If not specified, defaults to ``range(a.ndim)[::-1]``, which
        reverses the order of the axes.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    moveaxis
    argsort
    
    Notes
    -----
    Use `transpose(a, argsort(axes))` to invert the transposition of tensors
    when using the

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array shape:", arr.shape)
print(arr)
arr_transp = np.transpose(arr)
print("Transpose array shape:", arr_transp.shape)
print(arr_transp)
# + np.transpose([np.arange(0, 51, 10)])

Array shape: (2, 3)
[[1 2 3]
 [4 5 6]]
Transpose array shape: (3, 2)
[[1 4]
 [2 5]
 [3 6]]


## Updating Array Values

In [ ]:
arr[1][1] = 3
print(arr)    # value 5 is updated by 2

arr_transp[1, 1] = 2  # value 5 updated by 2
print("arr_transp:",arr_transp)

[[1 2 3]
 [4 3 6]]
arr_transp: [[1 4]
 [2 2]
 [3 6]]


## Total Number of Elements in the Array

In [ ]:
import numpy as np
help(np.size)

Help on function size in module numpy:

size(a, axis=None)
    Return the number of elements along a given axis.
    
    Parameters
    ----------
    a : array_like
        Input data.
    axis : int, optional
        Axis along which the elements are counted.  By default, give
        the total number of elements.
    
    Returns
    -------
    element_count : int
        Number of elements along the specified axis.
    
    See Also
    --------
    shape : dimensions of array
    ndarray.shape : dimensions of array
    ndarray.size : number of elements in array
    
    Examples
    --------
    >>> a = np.array([[1,2,3],[4,5,6]])
    >>> np.size(a)
    6
    >>> np.size(a,1)
    3
    >>> np.size(a,0)
    2



In [ ]:
arr.size

6

## Array of Random Numbers

In [ ]:
import numpy as np
help(np.random.random)

Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



In [ ]:
nr = np.random.random((4, 4)) # 2 dimensional array of 3 rows and 3 columns with random numbers
# Elements in array are randomly generated using the random function.
print(nr)

[[0.7675743  0.37500339 0.79654756 0.74308319]
 [0.31053198 0.73490103 0.6069545  0.14232139]
 [0.37909269 0.69830759 0.10064812 0.04478343]
 [0.37639264 0.47845034 0.60248801 0.86307427]]


## Array Functions

### `np.ones()`

Returns a new array of given shape and data type, where all the elements are set to 1.

`ones(shape, dtype=None, order='C')`

The shape is an int or tuple of ints to define the size of the array. If we just specify an int variable, a one-dimensional array will be returned. For a tuple of ints, the array of given shape will be returned.<br>
The dtype is an optional parameter with default value as a float. It’s used to specify the data type of the array, for example, int. <br>
The order defines the whether to store multi-dimensional array in row-major (C-style) or column-major (Fortran-style) order in memory.

In [ ]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [ ]:
c = np.ones((3, 2),dtype=int)
print(c)

[[1 1]
 [1 1]
 [1 1]]


### `np.zeros()`

It is identical to `np.ones()`, except that all the elements are initialized to zero.

In [ ]:
import numpy as np
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [ ]:
d = np.zeros((2, 4),dtype=int)
print(d)

[[0 0 0 0]
 [0 0 0 0]]


### `np.eye()`

Returns an array where all the elements are equal to zero, except diagonal elements that are initialized to 1.

In [ ]:
import numpy as np
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
    See Also
    -

In [ ]:
e = np.eye((3))  # This creates the popularly known Identity Matrix!
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Different dimensions of arrays created with np.eye
print(np.eye(5))
print()
print(np.eye(2,3))
print()
print(np.eye(3,3))
print()
print(np.eye(4, k=-3))
print()
print(np.eye(5, k=2))
print()
print(np.eye(2, 3))
print()
print(np.eye(5, dtype=int))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]]

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


### `full()`
Returns a new array with the same shape and type as a given, filled with the fill_value.
    
Syntax:

`full(shape, fill_value, dtype = None, order = 'C')`

In [ ]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
    
    See Also
    --------
    full_like : Return a new array with shape of input filled with value.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    zeros : Return a new array set

In [ ]:
e = np.full((5,3), 8) # Matrix of constant numbers
print(e)

[[8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]]


### `np.linspace()`

Returns number spaces evenly w.r.t the given interval start and stop. This functions is similar to arange but instead of step size it uses a sample number.

Syntax:

`numpy.linspace(start, stop, num = 50, endpoint = True, retstep = False, dtype = None)

In [ ]:
import numpy as np
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [ ]:
f = np.linspace(1, 10, 4) # Generate 4 equally spaced values between 1 and 10
print(f)

[ 1.  4.  7. 10.]


In [ ]:
# Sample other variations of linspace
print(np.linspace(1, 2, retstep=True))
print()
print(np.linspace(1, 100, num=5, retstep=True))
print()
a = np.linspace(1, 100, num=5, endpoint=False, retstep=True)
print(a)
print(a[0][0])
np.linspace(1, 100, num=5, retstep=True)
np.linspace(1, 100, num=5, dtype=int)

(array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ]), 0.02040816326530612)

(array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ]), 24.75)

(array([ 1. , 20.8, 40.6, 60.4, 80.2]), 19.8)
1.0


array([  1,  25,  50,  75, 100])

## Some interesting numpy functions

### Math functions
numpy has a fairly big set of functions to for mathematical operations

In [ ]:
# standard math functions, like mean, standard deviations, max, min, etc.
# are all available
a = np.array([10, 8, 9])

print(a)

print('Mean: ', np.mean(a))
print('Standard deviation: ', np.std(a))
print('Max: ', np.max(a))
print('Min: ', np.min(a))
print('Index Max: ', np.argmax(a)) #argmax in numpy
print('Index Min: ', np.argmin(a)) #argmin in numpy

[10  8  9]
Mean:  9.0
Standard deviation:  0.816496580927726
Max:  10
Min:  8
Ix Max:  0
Ix Min:  1


### Inserting and deleting elements

numpy are blocks of memory with a different layout than the list. For this reason it's not possible to append and element like a list, thoug similar functions are provided

In [ ]:
a = np.array([1, 2, 3])

b = np.append(a, 3); print(b) # insert the number 3 at the end
c = np.insert(a, 2, 12); print(c)  # insert the value 12 at index 2
d = np.delete(a, 1); print(d) # delete the value at index 1

[1 2 3 3]
[ 1  2 12  3]
[1 3]


In [ ]:
#math functions

a=np.array([(1,0,3),(3,4,5)])
print(a)

print(np.sqrt(a))
print()

print(np.std(a))
print()

print(np.log(a))
print()

b=np.sqrt(a)
print(b.round(2))

print(np.sqrt(a).round(2))

[[1 0 3]
 [3 4 5]]
[[1.         0.         1.73205081]
 [1.73205081 2.         2.23606798]]

1.699673171197595

[[0.               -inf 1.09861229]
 [1.09861229 1.38629436 1.60943791]]

[[1.   0.   1.73]
 [1.73 2.   2.24]]
[[1.   0.   1.73]
 [1.73 2.   2.24]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: RuntimeWarning: divide by zero encountered in log
  if sys.path[0] == '':


In [ ]:
?np.sqrt

In [ ]:
x= np.array([(1,2),(3,4),])
y= np.array([(5,6),(3,4),])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [3 4]]


In [ ]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)
print(x@y)
#print(np.dot(x,y))
#print(np.add(x,y))

#np.add(), np.subtract(), np.multiply(), np.divide(), np.remainder()

[[6 8]
 [6 8]]
[[-4 -4]
 [ 0  0]]
[[ 5 12]
 [ 9 16]]
[[0.2        0.33333333]
 [1.         1.        ]]
[[1 2]
 [0 0]]
[[11 14]
 [27 34]]


In [ ]:
#arrays are mutable
x= np.array([(1,2,3),(3,4,5)])
x[0,1]=7
print(x)

[[1 7 3]
 [3 4 5]]


In [ ]:
# ravel() functions returns contiguous flattened array
# (1D array with all the input-array elements and with the same type as it)

print(x)

y=x.ravel()
print(y)

[[1 7 3]
 [3 4 5]]
[1 7 3 3 4 5]


In [ ]:
y.reshape((2,3))

array([[1, 7, 3],
       [3, 4, 5]])

In [ ]:
z=np.array([1,2,3,4,5,6,7,8])
z.ndim

1

In [ ]:
z.reshape((2,4))



array([[1, 2, 3, 4],
       [5, 6, 7, 8]])